// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4729.FRC2019.subsystems;


import org.usfirst.frc4729.FRC2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.PWMTalonSRX;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Hatch extends Subsystem {
    int level;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private int numEjectPneumatics = 3;
    private DoubleSolenoid[] ejectPneumatics;
    private DoubleSolenoid extendPneumatic;
    private Compressor compressor;
    private DigitalInput limitTop;
    private DigitalInput limitBottom;
    private PWMTalonSRX winch1;
    private PWMTalonSRX winch2;
    private Encoder winchEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Hatch() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        ejectPneumatics = new DoubleSolenoid[numEjectPneumatics];
        for (int i = 0; i < numEjectPneumatics; i++) {
            ejectPneumatics[i] = new DoubleSolenoid(0, 0, 1);
            addChild("EjectPneumatic1",ejectPneumatics[i]);
        }
        
        extendPneumatic = new DoubleSolenoid(0, 6, 7);
        addChild("ExtendPneumatic",extendPneumatic);
        
        
        compressor = new Compressor(0);
        addChild("Compressor",compressor);
        
        
        limitTop = new DigitalInput(0);
        addChild("LimitTop",limitTop);
        
        limitBottom = new DigitalInput(1);
        addChild("LimitBottom",limitBottom);
        
        
        winch1 = new PWMTalonSRX(1);
        addChild("Winch1",winch1);
        winch1.setInverted(false);
        
        winch2 = new PWMTalonSRX(3);
        addChild("Winch2",winch2);
        winch2.setInverted(false);
        
        winchEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        addChild("WinchEncoder",winchEncoder);
        winchEncoder.setDistancePerPulse(1.0);
        winchEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        updateWinch();
    }

    int[] levels = {100, 200, 300};
    int slowRange = 50;
    int stopRange = 10;
    double minPower = 0.5;
    public void updateWinch() {
        if (limitTop.get() || limitBottom.get()) {
            move(0);
        } else {
            int difference = levels[level] - winchEncoder.get();
            float direction = Math.signum(difference);
            difference = Math.abs(difference);
            if (difference < stopRange) {
                move(0);
            } else if (difference < slowRange) {
                move(((difference / slowRange) * (1 - minPower) + minPower) * direction);
            } else {
                move(direction);
            }
        }
    }

    private void move(double power) {
        winch1.set(power);
        winch2.set(power);
    }

    public void extend() {
        extendPneumatic.set(DoubleSolenoid.Value.kForward);
    }

    public void retract() {
        extendPneumatic.set(DoubleSolenoid.Value.kReverse);
    }

    public void eject() {
        setEjectPneumatics(DoubleSolenoid.Value.kForward);
    }

    public void uneject() {
        setEjectPneumatics(DoubleSolenoid.Value.kReverse);
    }

    private void setEjectPneumatics(DoubleSolenoid.Value value) {
        for (int i = 0; i < numEjectPneumatics; i++) {
            ejectPneumatics[i].set(value);
        }
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

